### ISSUE TITLE
Does not get back t o list after clicking on Save Button

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#13]
**Path:** High Court Case > Create 
**Issue:** Clicking on the Save button does not take back to the list.
![save button](https://user-images.githubusercontent.com/54391338/63645779-6a256b80-c727-11e9-9b16-55e13f7ed9d5.png)

**Comment by anil-jaglan** [comment]
In legal module, while creating a legal case, Save button will save the data on server and will not redirect to any list or on other page. It's because form is being saved in two part. First with basic information and second with extended info. So there is not point to redirect the user to list as it will more difficult for him/her to fill the information after every save.

**Comment by ghost** [comment]
After Clicking on the Last **Save** Button User should be back on the List. As Well As No **Back** Button is Provided. What if the User needs to get Back to the List? 
There must be a **Back** button or redirect back to the list after clicking on the **Save** Button.

**Comment by ghost** [comment]
not fixed
